function map = column_mapping()
% COLUMN_MAPPING Returns a struct mapping table keys to column indices
% Update this file if the column order changes for any table/year

map = struct( ...
    'ALT_Table2020_22', struct('Age', 1, 'qx', 5, 'lx', 2), ...
    'ALT_Table2015_17', struct('Age', 1, 'qx', 5, 'lx', 2), ...
    'ALT_Table2010_12', struct('Age', 1, 'qx', 5, 'lx', 2), ...
    'ALT_Table2005_07', struct('Age', 1, 'qx', 5, 'lx', 2) ...
);
end 